steps:   
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache bind-tools
        if dig +short github.com | grep -E '^[0-9.]+$' > /dev/null; then
          echo "DNS lookup successful"
        else
          echo "DNS lookup failed for domain.com"
          exit 1
        fi
    id: 'dns-check'
logsBucket: 'gs://logs-bucket-demo'
options:
  logging: GCS_ONLY
  pool:
    name: 'projects/manuelmata-dev/locations/us-central1/workerPools/private-pool-with-nat'
