steps:
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      apk add --no-cache bind-tools
      IP=$(dig +short github.com | grep -E '^[0-9.]+$')
      if [ -n "$IP" ]; then
        echo "DNS lookup successful, IP: $IP"
      else
        echo "DNS lookup failed for github.com"
        exit 1
  id: 'dns-check'
logsBucket: 'gs://logs-bucket-demo'
options:
  logging: GCS_ONLY
  pool:
    name: 'projects/manuelmata-dev/locations/us-central1/workerPools/private-pool-with-nat'
